# Generated by Django 3.1.4 on 2020-12-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(null=True, upload_to='actors/', verbose_name='Poster'),
        ),
    ]
