# Generated by Django 3.1.4 on 2020-12-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20201227_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(related_name='film_genre', to='movie.Genre', verbose_name='Genres'),
        ),
    ]
