# Generated by Django 3.1.4 on 2020-12-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20201227_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Title'),
        ),
    ]
